### ISSUE TITLE
No scripts in http://cemantix.org/data/ontonotes.html

### ISSUE THREAD

**Issue by zhiyuanpeng** [allanj/pytorch_neural_crf#18]

**Comment by allanj** [comment]
It seems they have removed the link. Please download it here, I upload the script in google drive.
https://drive.google.com/file/d/1UAy_DAisnFvKap0vxgTAsj_Vx8VBxQyV/view?usp=sharing

**Comment by zhiyuanpeng** [comment]
Thanks, but I find the scripts you send me are same with the skeleton2conll.py and skeleton2conll.sh listed in http://consumer.cemantix.org/2012/data.html.

**Comment by allanj** [comment]
Thanks. That will be great

**Comment by hankcs** [comment]
> Thanks, but I find the scripts you send me are same with the skeleton2conll.py and skeleton2conll.sh listed in http://consumer.cemantix.org/2012/data.html.
> […](#)
> Sent from my iPhone
> On Aug 24, 2020, at 10:14 PM, Allan Jie ***@***.***> wrote: It seems they have removed the link. Please download it here, I upload the script in google drive. https://drive.google.com/file/d/1UAy_DAisnFvKap0vxgTAsj_Vx8VBxQyV/view?usp=sharing — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No, the .sh files are not the same.

![hankcs com 2021-01-05 at 2 57 37 PM](https://user-images.githubusercontent.com/5326890/103692865-6a15bc80-4f66-11eb-82b7-b602f4d0f2a9.png)

@allanj 's script is creating a `conll-2012-test` partition and that one is the test set for conll 2012.
