### ISSUE TITLE
No Reader file in config folder

### ISSUE THREAD

**Issue by JingliSHI0206** [allanj/pytorch_neural_crf#19]
May i know where reader file is?

**Comment by allanj** [comment]
I found that I suddenly push some unfinished changes to the latest commit.
Can you try `git pull` again, and you should be able to get everything.

**Comment by JingliSHI0206** [comment]
> I found that I suddenly push some unfinished changes to the latest commit.
> Can you try `git pull` again, and you should be able to get everything.

thank you
