### ISSUE TITLE
Can not run ner_predictor.py

### ISSUE THREAD

**Issue by Just4Uzi** [allanj/pytorch_neural_crf#35]
Hi allanj

I trained a lstm-crf model, and try to predict by runing ner_predictor.py, but it seems like that this file need to update。
I can not find simple_batching function or Sentence class

thank you

**Comment by allanj** [comment]
Sure. I will get it updated by today

**Comment by Just4Uzi** [comment]
thank you very much

**Comment by allanj** [comment]
Feel free to reopen
