### ISSUE TITLE
Use custom pre-trained BERT models

### ISSUE THREAD

**Issue by NiteshMethani** [allanj/pytorch_neural_crf#39]
Hi,
Suppose we have pretrained BERT on custom dataset.
How do we use this BERT model instead of default Hugging Face model?

Follow up question:
I understand that the repo has a feature to use ELMo/BERT's contextual embeddings in a static manner by pre-computing the embeddings for the whole dataset. Any suggestion on how to do this or where to look in the code?

**Comment by allanj** [comment]
> Suppose we have pretrained BERT on custom dataset.
> How do we use this BERT model instead of default Hugging Face model?

just need to revise the name of `from_pretrained`, just like what you did in HuggingFace

> I understand that the repo has a feature to use ELMo/BERT's contextual embeddings in a static manner by pre-computing the embeddings for the whole dataset. Any suggestion on how to do this or where to look in the code?

You can find the information here:
 https://github.com/allanj/pytorch_neural_crf/blob/master/preprocess

**Comment by NiteshMethani** [comment]
This helps. Thank you!
