### ISSUE TITLE
Can you tell  me what is the forward_labeld and foward_unlabeld?

### ISSUE THREAD

**Issue by zshy1205** [allanj/pytorch_neural_crf#6]
Can you give some advice about read your code?
why the loss use forward_labeld and foward_unlabeld?

**Comment by mxc19912008** [comment]
This might be helpful: https://github.com/allanj/pytorch_lstmcrf/issues/4#issuecomment-526368279

**Comment by zshy1205** [comment]
Thanks

**Comment by allanj** [comment]
Thanks @mxc19912008 . To briefly elaborate more about this: `forward_labeled` calculates the score (in log-space) corresponds to the gold path. `forward_unlabeled` calculate the sum of the scores (in log-space) that corresponds to all the possible paths.
