### ISSUE TITLE
How to use the ELMo/BERT model to do fine tune 

### ISSUE THREAD

**Issue by Anikacyp** [allanj/pytorch_neural_crf#7]
It seems ELMo/BERT has the same functions as glove, Can you tell me how to use the hidden size of BERT to do fine-tune. Say train the BERT parameters at the same time.

**Comment by allanj** [comment]
At the moment, we are not supporting this feature yet. I plan to support this soon but the next ACL deadline is approaching. But what I would suggest is to incorporate the transformer package by hugging face. (https://github.com/huggingface/transformers)
